### ISSUE TITLE
Environment variable not working?

### ISSUE THREAD

**Issue by tombell** [boxen/puppet-go#5]
Installed this module adding getting the following error every time I reload my shell.

```
/opt/boxen/env.d/99_chgo_auto.sh:source:1: no such file or directory: //share/chgo/auto.sh
```

**Comment by nomasprime** [comment]
This still seems to be an issue, please re-open.

**Comment by salimane** [comment]
+1

**Comment by tombell** [comment]
It's a bug in chgo. You should manually install Go and not use puppet-go.

**Comment by theazureshadow** [comment]
I ran into this when trying to source 99_chgo_auto.sh in zsh on Mac OS. Using bash worked fine.

**Comment by erikvanoosten** [comment]
I just ran into this after a boxen run, while before it worked fine for at least a year. Also using zsh on Mac OSX. So its probably related to #8 .
